var storeHeader = '<header><nav data-navigation-style="' + USER("Navigation Style") + '" class="navbar ' + (USER("Navigation Style").indexOf('Centered') > -1 ? 'd-lg-block ' : '') + 'fixed-top' + (USER("Navigation Style").indexOf('Condensed') == -1 ? ' navbar-expand-lg' : '') + ' py-0 px-4">' +
					  (USER("Navigation Style") == 'Centered Alternative' || USER("Navigation Style") == 'Standard Alternative' ? '<div class="collapse d-flex navbar-collapse" id=""><ul class="navbar-nav container mx-auto justify-content-end">' +  (USER("Navigation Style").indexOf('Centered Alternative') ? topNavLinks : '') + '</ul></div>' : '') +
					  '<div class="store-logo ' + (USER("Navigation Style").indexOf('Centered') > -1 ? 'd-lg-flex col-6 col-lg-12 py-4 pb-lg-0 px-0 d-inline-block justify-content-center' : '') + '"><a class="navbar-brand py-3" href="/">' + (USER("Logo Image URL") ? '<img src=' + USER("Logo Image URL").replace(logoA, logoB) + '>' : USER("Store Name") ) + '</a></div>\
					  <ul data-nav-view="condensed" class="navbar-nav flex-row ' + (USER("Navigation Style").indexOf('Condensed') > -1 ? '' : 'd-lg-none d-flex') + ' px-0 py-4 ml-auto">\
						<li class="nav-item px-2"><a href="#" class="py-0 search-btn open-search btn btn-link px-1 collapsed" data-toggle="modal" data-target="#search-modal-btn" aria-expanded="false"><i class="material-icons">search</i></a></li>\
						<li class="nav-item px-2"><a href="/cart"' + (window.location.href.indexOf('TEMP_MINICART_REMOVAL') == -1 ? ' ' : ' data-toggle="modal" data-target="#cart-modal-btn"') + ' class="nav-link p-0"><i class="material-icons">shopping_basket</i></a></li>\
						<li class="nav-item px-2"><a href="#" class="py-0 px-1 btn btn-link collapsed" data-toggle="modal" data-target="#menu-modal-btn" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><i class="material-icons">menu</i></a></li>\
					  </ul>\
					  <div class="collapse navbar-collapse" id="navbarSupportedContent"><ul data-nav-view="expanded" class=" navbar-nav ' + (USER("Navigation Style").indexOf('Centered Alternative') > -1 ? 'container justify-content-between ' : '') + (USER("Navigation Style").indexOf('Condensed') > -1 ? 'd-flex d-lg-none ' : '') +  (USER("Navigation Style").indexOf('Centered') > -1 ? 'mx-auto' : 'ml-auto') + '">' + standardNavLinks + '</ul></div>\
					</nav></header>' + menuModal + flyoutCart;